const app=document.getElementById('app');
const services=['Telegram','MAX','VK','WhatsApp','Яндекс','Instagram','Google','Facebook','Wildberries','Ozon'];
const s={user:null,screen:'home',mode:null,service:null,listings:[],orders:[]};
const e=x=>String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function render(){({home,login,register,services:list,offers,sell,order,orders,balance,support}[s.screen]||home)()}
function shell(t,b){app.innerHTML=`<main class="wrap"><div class="top"><button class="back" onclick="go('home')">‹ Назад</button><span class="pill">${s.user?e(s.user.login):'Гость'}</span></div><h2>${t}</h2>${b}</main>`}
function home(){app.innerHTML=`<main class="wrap"><div class="brand"><h1>Lemur-Priemka</h1><div class="muted">Маркетплейс предложений</div></div><div class="card"><button class="btn" onclick="start('buy')">Купить номер</button><button class="btn alt" onclick="start('sell')">Задать номер</button></div><div class="card"><button class="btn alt" onclick="go('login')">Войти</button><button class="btn alt" onclick="go('register')">Зарегистрироваться</button></div><div class="notice">Средства резервируются до завершения сделки. Сайт не перехватывает и не пересылает одноразовые коды сторонних сервисов.</div></main>`}
function auth(reg){shell(reg?'Регистрация':'Вход',`<div class="card"><input class="input" id="l" placeholder="Логин"><input class="input" id="p" type="password" placeholder="Пароль">${reg?'<input class="input" id="p2" type="password" placeholder="Повторите пароль">':''}<button class="btn" onclick="${reg?'reg()':'log()'}">${reg?'Зарегистрироваться':'Войти'}</button></div>`)}
function log(){let l=document.getElementById('l').value.trim();if(!l)return alert('Введите логин');s.user={login:l,balance:10};s.screen=s.mode?'services':'home';render()}
function reg(){let l=document.getElementById('l').value.trim(),p=document.getElementById('p').value,p2=document.getElementById('p2').value;if(!l||!p)return alert('Заполните поля');if(p!==p2)return alert('Пароли не совпадают');s.user={login:l,balance:10};s.screen=s.mode?'services':'home';render()}
function start(m){s.mode=m;if(!s.user){s.screen='login';return render()}s.screen='services';render()}
function services(){shell(s.mode==='buy'?'Купить номер':'Задать номер',`<div class="grid">${services.map(x=>`<button class="service" onclick="choose('${x}')"><b>${x}</b><span class="muted">${s.mode==='buy'?'Предложения':'Выставить номер'}</span></button>`).join('')}</div>`)}
function choose(x){s.service=x;s.screen=s.mode==='buy'?'offers':'sell';render()}
function offers(){let a=s.listings.filter(x=>x.service===s.service);shell(s.service,a.length?a.map((x,i)=>`<div class="card"><div class="row"><b>${e(x.masked)}</b><span class="price">$${x.total.toFixed(2)}</span></div><div class="muted">Продавцу $${x.price.toFixed(2)} · комиссия $${x.fee.toFixed(2)}</div><button class="btn" onclick="buy(${i})">Купить</button></div>`).join(''):'<div class="card muted">Нет доступных предложений.</div>')}
function sell(){shell('Выставить номер',`<div class="card"><input class="input" value="${e(s.service)}" disabled><input class="input" id="n" placeholder="Номер"><input class="input" id="pr" type="number" step=".01" placeholder="Цена продавца, $"><button class="btn" onclick="add()">Выставить</button></div>`)}
function add(){let n=document.getElementById('n').value.trim(),p=Number(document.getElementById('pr').value);if(!n||!p)return alert('Заполните поля');let fee=.5;s.listings.push({service:s.service,seller:s.user.login,number:n,masked:'••••'+n.slice(-4),price:p,fee,total:p+fee});alert('Предложение выставлено');go('services')}
function buy(i){let a=s.listings.filter(x=>x.service===s.service),x=a[i];if(s.user.balance<x.total)return alert('Недостаточно средств');s.user.balance-=x.total;s.orders.push({...x,buyer:s.user.login,status:'reserved'});s.listings=s.listings.filter(y=>y!==x);s.screen='order';render()}
function order(){let o=s.orders.at(-1);shell('Сделка',`<div class="card"><b>${e(o.service)}</b><p>Продавец: ${e(o.seller)}</p><p>Покупатель: ${e(o.buyer)}</p><p>Резерв: $${o.total.toFixed(2)}</p><span class="pill">${o.status}</span></div><div class="card"><div class="notice">В чате сделки можно передавать обычные данные заказа. OTP-коды сторонних сервисов не обрабатываются.</div><button class="btn" onclick="release()">💰 Передать деньги продавцу</button><button class="btn alt" onclick="support()">🆘 Вызвать поддержку</button></div>`)}
function release(){let o=s.orders.at(-1);o.status='completed';alert('Сделка завершена: продавцу $'+o.price.toFixed(2)+', комиссии платформы $'+o.fee.toFixed(2));render()}
function orders(){shell('Мои сделки',s.orders.length?s.orders.map(o=>`<div class="card"><b>${e(o.service)}</b><div class="muted">$${o.total.toFixed(2)} · ${o.status}</div></div>`).join(''):'<div class="card muted">Пока нет сделок.</div>')}
function balance(){shell('Баланс',`<div class="card"><div class="price">$${s.user?.balance.toFixed(2)||'0.00'}</div></div>`)}
function support(){shell('Поддержка',`<div class="card"><textarea class="input" rows="5" placeholder="Опишите проблему"></textarea><button class="btn" onclick="alert('Обращение отправлено')">Отправить</button></div>`)}
function go(x){s.screen=x;render()} render();